#!/bin/bash
set -euo pipefail

for variable in RING_STATS_TEST_MODE RING_STATS_TEST_ROOT TEST_PROJECT_DIR APPROVAL_DIR APP_PATH ARTIFACT_APP_PATH CANDIDATE_MANIFEST MANIFEST_HASH_PATH USER_APPLICATIONS_DIR TRASH_DIR OSASCRIPT_BIN QUIT_RUNNING_CHECK_BIN LAUNCH_RUNNING_CHECK_BIN CODESIGN_BIN LSREGISTER_BIN MDIMPORT_BIN OPEN_BIN RING_STATS_INSTALL_FAIL_AT; do
  if [[ -n "${!variable:-}" ]]; then
    echo "error: production entrypoint refuses test override: $variable" >&2
    exit 1
  fi
done
